In [1]:
import pandas as pd
import nltk 
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import naive_bayes
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split
import numpy as np

In [2]:
df= pd.read_csv('prueba.txt',sep='\t', names=['categ','txt'], encoding='latin-1')

In [3]:
df.head()

categ                             txt
0      1                 que bonito dia.
1      1           estuvo genial el dia.
2      1            que buenas noticias.
3      3                Sexo y nada mas.
4      3  Estas caliente para la fiesta.

In [4]:
#convertir a numeros usando tf-idf
stopset = set(stopwords.words('spanish'))
vectorizer= TfidfVectorizer(use_idf=True, lowercase=True, strip_accents='ascii', stop_words=stopset)

In [5]:
#Aqui decimos que texto va ser nuestra y nuestra varible que se va a entrenar
y=df.categ

In [6]:
X=vectorizer.fit_transform(df.txt)

C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:388: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['eramos', 'estabamos', 'estais', 'estan', 'estara', 'estaran', 'estaras', 'estare', 'estareis', 'estaria', 'estariais', 'estariamos', 'estarian', 'estarias', 'esteis', 'esten', 'estes', 'estuvieramos', 'estuviesemos', 'fueramos', 'fuesemos', 'habeis', 'habia', 'habiais', 'habiamos', 'habian', 'habias', 'habra', 'habran', 'habras', 'habre', 'habreis', 'habria', 'habriais', 'habriamos', 'habrian', 'habrias', 'hayais', 'hubieramos', 'hubiesemos', 'mas', 'mia', 'mias', 'mio', 'mios', 'seais', 'sera', 'seran', 'seras', 'sere', 'sereis', 'seria', 'seriais', 'seriamos', 'serian', 'serias', 'si', 'tambien', 'tendra', 'tendran', 'tendras', 'tendre', 'tendreis', 'tendria', 'tendriais', 'tendriamos', 'tendrian', 'tendrias', 'teneis', 'tengais', 'tenia', 'teniais', 'teniamos', 'tenian', 'tenias', 't

In [7]:
print (y.shape)
print (X.shape)

(398,)
(398, 742)


In [8]:
X_train, X_test,y_train, y_test = train_test_split(X, y, random_state=42)

In [11]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier

In [12]:
clf=DecisionTreeClassifier()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [30]:
#este es 3 movie_reviews_array=np.array(["Ya no tiene excusa Hoy salió con su amiga, dizque pa' matar la tusa Que porque un hombre le pagó mal Está dura y abusa Se cansó de ser buena, ahora es ella quien los usa Que porque un hombre le pagó mal Ya no se le ve sentimental Dice que por otro man no llora, no Pero si le ponen la canción Le da una depresión tonta Llorando lo comienza a llamar Pero él la dejó en buzón Será porque con otra está Fingiendo que a otra se puede amar"])
movie_reviews_array=np.array(["Ella tiene maldad, ella tiene una diabla guardá' Loco por darle una nalgá' que la deje marcá' Lo prende, al frente de él lo guarda Esa tipa es una descará' Ella tiene maldad, ella tiene una diabla guardá' Loco por darle una nalgá' que la deje marcá' Lo prende, al frente de él lo guarda Y al frente de la mai lo guarda"])
movie_review_vector = vectorizer.transform(movie_reviews_array)
print ("Resultado : ",clf.predict(movie_review_vector))

Resultado :  [2]


In [31]:
from sklearn import metrics
print("Accuracy score:",metrics.accuracy_score(y_test, y_pred))
print("Presicion score:",metrics.precision_score(y_test, y_pred, average='macro'))
print("Recall score:",metrics.recall_score(y_test, y_pred, average='macro'))
print("f1 score:",metrics.f1_score(y_test, y_pred, average='macro'))


Accuracy score: 0.52
Presicion score: 0.45576728343919726
Recall score: 0.4264298311917359
f1 score: 0.41750841750841744


In [32]:
from sklearn.metrics import confusion_matrix
#print(metrics.classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

[[40  5  4]
 [15  4  5]
 [16  3  8]]
