In [208]:
import pandas as pd
import nltk 
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import naive_bayes
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split
import numpy as np

In [209]:
#importamos la base de datos
df= pd.read_csv('baseDatos.txt',sep='\t', names=['categ','txt'], encoding='latin-1')

In [210]:
df.head()

categ                             txt
0      1                 que bonito dia.
1      1           estuvo genial el dia.
2      1            que buenas noticias.
3      3                Sexo y nada mas.
4      3  Estas caliente para la fiesta.

In [211]:
#convertir a numeros usando tf-idf
stopset = set(stopwords.words('spanish'))
vectorizer= TfidfVectorizer(use_idf=True, lowercase=True, strip_accents='ascii', stop_words=stopset)

In [212]:
y=df.categ

In [213]:
X=vectorizer.fit_transform(df.txt)

C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:388: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['eramos', 'estabamos', 'estais', 'estan', 'estara', 'estaran', 'estaras', 'estare', 'estareis', 'estaria', 'estariais', 'estariamos', 'estarian', 'estarias', 'esteis', 'esten', 'estes', 'estuvieramos', 'estuviesemos', 'fueramos', 'fuesemos', 'habeis', 'habia', 'habiais', 'habiamos', 'habian', 'habias', 'habra', 'habran', 'habras', 'habre', 'habreis', 'habria', 'habriais', 'habriamos', 'habrian', 'habrias', 'hayais', 'hubieramos', 'hubiesemos', 'mas', 'mia', 'mias', 'mio', 'mios', 'seais', 'sera', 'seran', 'seras', 'sere', 'sereis', 'seria', 'seriais', 'seriamos', 'serian', 'serias', 'si', 'tambien', 'tendra', 'tendran', 'tendras', 'tendre', 'tendreis', 'tendria', 'tendriais', 'tendriamos', 'tendrian', 'tendrias', 'teneis', 'tengais', 'tenia', 'teniais', 'teniamos', 'tenian', 'tenias', 't

In [214]:
print (y.shape)
print (X.shape)

(398,)
(398, 742)


In [215]:
X_train, X_test,y_train, y_test = train_test_split(X, y, random_state=42)

In [216]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler(with_mean=False)
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [224]:
from sklearn.neighbors import KNeighborsClassifier
clf=KNeighborsClassifier(n_neighbors=15)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [225]:
movie_reviews_array=np.array(["Hoy enfrento mi verdad Eres dueño de tu cuerpo Y yo sigo siendo el mismo que va en busca de tu amor Antes no podía ver Ya que me quite las vendas veo que mueres por él Y si te vas Quien me dará Todo lo que siempre soñé Quien le dirá al corazón Que jamás nunca te tendré"])
movie_review_vector = vectorizer.transform(movie_reviews_array)
#mostramos el resultado del analisis de la letra
print (clf.predict(movie_review_vector))

[3]


In [226]:
from sklearn import metrics
print("Accuracy score:",metrics.accuracy_score(y_test, y_pred))
print("Presicion score:",metrics.precision_score(y_test, y_pred, average='macro'))
print("Recall score:",metrics.recall_score(y_test, y_pred, average='macro'))
print("f1 score:",metrics.f1_score(y_test, y_pred, average='macro'))

Accuracy score: 0.27
Presicion score: 0.09000000000000001
Recall score: 0.3333333333333333
f1 score: 0.14173228346456693


C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [144]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 6  0 38]
 [ 1  1 15]
 [ 2  0 34]]
              precision    recall  f1-score   support

           1       0.67      0.14      0.23        44
           2       1.00      0.06      0.11        17
           3       0.39      0.94      0.55        36

    accuracy                           0.42        97
   macro avg       0.69      0.38      0.30        97
weighted avg       0.62      0.42      0.33        97

