In [206]:
import pandas as pd
import nltk 
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import naive_bayes
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split
import numpy as np

In [207]:
#importamos la base de datos
df= pd.read_csv('baseDatos.txt',sep='\t', names=['categ','txt'], encoding='latin-1')

In [208]:
df.head()

categ                             txt
0      1                 que bonito dia.
1      1           estuvo genial el dia.
2      1            que buenas noticias.
3      3                Sexo y nada mas.
4      3  Estas caliente para la fiesta.

In [209]:
#convertir a numeros usando tf-idf
stopset = set(stopwords.words('spanish'))
vectorizer= TfidfVectorizer(use_idf=True, lowercase=True, strip_accents='ascii', stop_words=stopset)

In [210]:
y=df.categ

In [211]:
X=vectorizer.fit_transform(df.txt)

C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:388: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['eramos', 'estabamos', 'estais', 'estan', 'estara', 'estaran', 'estaras', 'estare', 'estareis', 'estaria', 'estariais', 'estariamos', 'estarian', 'estarias', 'esteis', 'esten', 'estes', 'estuvieramos', 'estuviesemos', 'fueramos', 'fuesemos', 'habeis', 'habia', 'habiais', 'habiamos', 'habian', 'habias', 'habra', 'habran', 'habras', 'habre', 'habreis', 'habria', 'habriais', 'habriamos', 'habrian', 'habrias', 'hayais', 'hubieramos', 'hubiesemos', 'mas', 'mia', 'mias', 'mio', 'mios', 'seais', 'sera', 'seran', 'seras', 'sere', 'sereis', 'seria', 'seriais', 'seriamos', 'serian', 'serias', 'si', 'tambien', 'tendra', 'tendran', 'tendras', 'tendre', 'tendreis', 'tendria', 'tendriais', 'tendriamos', 'tendrian', 'tendrias', 'teneis', 'tengais', 'tenia', 'teniais', 'teniamos', 'tenian', 'tenias', 't

In [212]:
print (y.shape)
print (X.shape)

(398,)
(398, 742)


In [213]:
X_train, X_test,y_train, y_test = train_test_split(X, y, random_state=42)

In [214]:
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression(random_state=0)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [218]:
movie_reviews_array=np.array(["Hoy enfrento mi verdad Eres dueño de tu cuerpo Y yo sigo siendo el mismo que va en busca de tu amor Antes no podía ver Ya que me quite las vendas veo que mueres por él Y si te vas Quien me dará Todo lo que siempre soñé Quien le dirá al corazón Que jamás nunca te tendré"])
movie_review_vector = vectorizer.transform(movie_reviews_array)
#Mostramos el resultado
print (clf.predict(movie_review_vector))

[1]


In [216]:
from sklearn import metrics
print("Accuracy score:",metrics.accuracy_score(y_test, y_pred))
print("Presicion score:",metrics.precision_score(y_test, y_pred, average='macro'))
print("Recall score:",metrics.recall_score(y_test, y_pred, average='macro'))
print("f1 score:",metrics.f1_score(y_test, y_pred, average='macro'))

Accuracy score: 0.56
Presicion score: 0.46928518242740136
Recall score: 0.4434681279919375
f1 score: 0.4096996753246753


In [217]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[45  2  2]
 [18  1  5]
 [16  1 10]]
              precision    recall  f1-score   support

           1       0.57      0.92      0.70        49
           2       0.25      0.04      0.07        24
           3       0.59      0.37      0.45        27

    accuracy                           0.56       100
   macro avg       0.47      0.44      0.41       100
weighted avg       0.50      0.56      0.48       100

